//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComenziAprovizionari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComenziAprovizionari()
        {
            this.RandComenziAprovizionareProduse = new HashSet<RandComenziAprovizionareProduse>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeLaFurnizorId { get; set; }
        public Nullable<int> CatreDepozitCentralId { get; set; }
        public Nullable<int> DeLaDepozitCentralId { get; set; }
        public Nullable<int> CatreMagazinId { get; set; }
        public System.DateTime DataCreare { get; set; }
        public Nullable<System.DateTime> DataPrimire { get; set; }
        public int StatusComanda { get; set; }
        public int IdUtilizator { get; set; }
    
        public virtual Furnizori Furnizori { get; set; }
        public virtual Magazine Magazine { get; set; }
        public virtual Magazine DeLaDepozitCentral { get; set; }
        public virtual Magazine CatreDepozitCentral { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandComenziAprovizionareProduse> RandComenziAprovizionareProduse { get; set; }
    }
}
