//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comenzi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comenzi()
        {
            this.RandComenziProduse = new HashSet<RandComenziProduse>();
        }
    
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public int IdUtilizator { get; set; }
        public int IdClient { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandComenziProduse> RandComenziProduse { get; set; }
        public virtual ViziteMedicale ViziteMedicale { get; set; }
    }
}
