//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furnizori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furnizori()
        {
            this.Produse = new HashSet<Produse>();
        }
    
        public int Id { get; set; }
        public string Denumire { get; set; }
        public string CIF { get; set; }
        public string Email { get; set; }
        public string NumarTelefon { get; set; }
        public string Adresa { get; set; }
        public string NRREGCOMERTULUI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produse> Produse { get; set; }
    }
}
