//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventar
    {
        public int Id { get; set; }
        public int CantitateDisponibila { get; set; }
        public int IdMagazin { get; set; }
        public int IdProdus { get; set; }
    
        public virtual Magazine Magazine { get; set; }
        public virtual Produse Produse { get; set; }
    }
}
