//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LicentaDbContext : DbContext
    {
        public LicentaDbContext()
            : base("name=LicentaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clienti> Clienti { get; set; }
        public virtual DbSet<Comenzi> Comenzi { get; set; }
        public virtual DbSet<DetaliiProdus> DetaliiProdus { get; set; }
        public virtual DbSet<Furnizori> Furnizori { get; set; }
        public virtual DbSet<Inventar> Inventar { get; set; }
        public virtual DbSet<Magazine> Magazine { get; set; }
        public virtual DbSet<Preturi> Preturi { get; set; }
        public virtual DbSet<Produse> Produse { get; set; }
        public virtual DbSet<RandComenziProduse> RandComenziProduse { get; set; }
        public virtual DbSet<Roluri> Roluri { get; set; }
        public virtual DbSet<Utilizatori> Utilizatori { get; set; }
        public virtual DbSet<ViziteMedicale> ViziteMedicale { get; set; }
        public virtual DbSet<ComenziAprovizionari> ComenziAprovizionari { get; set; }
        public virtual DbSet<RandComenziAprovizionareProduse> RandComenziAprovizionareProduse { get; set; }
    
        public virtual int P_LOGIN(string x, string y, ObjectParameter z)
        {
            var xParameter = x != null ?
                new ObjectParameter("X", x) :
                new ObjectParameter("X", typeof(string));
    
            var yParameter = y != null ?
                new ObjectParameter("Y", y) :
                new ObjectParameter("Y", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_LOGIN", xParameter, yParameter, z);
        }
    
        public virtual int FILTREAZAPRODUSE_DENUMIRE(string p_DENUMIRE)
        {
            var p_DENUMIREParameter = p_DENUMIRE != null ?
                new ObjectParameter("P_DENUMIRE", p_DENUMIRE) :
                new ObjectParameter("P_DENUMIRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FILTREAZAPRODUSE_DENUMIRE", p_DENUMIREParameter);
        }
    
        public virtual int P_AFISARECLIENT(string p_TELEFON, ObjectParameter p_NUME, ObjectParameter p_PRENUME, ObjectParameter p_EMAIL)
        {
            var p_TELEFONParameter = p_TELEFON != null ?
                new ObjectParameter("P_TELEFON", p_TELEFON) :
                new ObjectParameter("P_TELEFON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_AFISARECLIENT", p_TELEFONParameter, p_NUME, p_PRENUME, p_EMAIL);
        }
    
        public virtual ObjectResult<GetTopLentile_Result> GetTopLentile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopLentile_Result>("GetTopLentile");
        }
    
        public virtual ObjectResult<GetStatisticaMagazineDupaCantitati_Result> GetStatisticaMagazineDupaCantitati(string p_dataStart, string p_dataFinala)
        {
            var p_dataStartParameter = p_dataStart != null ?
                new ObjectParameter("p_dataStart", p_dataStart) :
                new ObjectParameter("p_dataStart", typeof(string));
    
            var p_dataFinalaParameter = p_dataFinala != null ?
                new ObjectParameter("p_dataFinala", p_dataFinala) :
                new ObjectParameter("p_dataFinala", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStatisticaMagazineDupaCantitati_Result>("GetStatisticaMagazineDupaCantitati", p_dataStartParameter, p_dataFinalaParameter);
        }
    
        public virtual ObjectResult<GetStatisticaMagazineDupaVanzari_Result> GetStatisticaMagazineDupaVanzari(string p_dataStart, string p_dataFinala)
        {
            var p_dataStartParameter = p_dataStart != null ?
                new ObjectParameter("p_dataStart", p_dataStart) :
                new ObjectParameter("p_dataStart", typeof(string));
    
            var p_dataFinalaParameter = p_dataFinala != null ?
                new ObjectParameter("p_dataFinala", p_dataFinala) :
                new ObjectParameter("p_dataFinala", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStatisticaMagazineDupaVanzari_Result>("GetStatisticaMagazineDupaVanzari", p_dataStartParameter, p_dataFinalaParameter);
        }
    
        public virtual ObjectResult<GetTopOchelariSoare_Result> GetTopOchelariSoare(string p_dataStart, string p_dataFinala)
        {
            var p_dataStartParameter = p_dataStart != null ?
                new ObjectParameter("p_dataStart", p_dataStart) :
                new ObjectParameter("p_dataStart", typeof(string));
    
            var p_dataFinalaParameter = p_dataFinala != null ?
                new ObjectParameter("p_dataFinala", p_dataFinala) :
                new ObjectParameter("p_dataFinala", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopOchelariSoare_Result>("GetTopOchelariSoare", p_dataStartParameter, p_dataFinalaParameter);
        }
    
        public virtual ObjectResult<PivotTableTotalVanzari_Result> PivotTableTotalVanzari()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PivotTableTotalVanzari_Result>("PivotTableTotalVanzari");
        }
    }
}
