//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magazine()
        {
            this.Inventar = new HashSet<Inventar>();
            this.Utilizatori = new HashSet<Utilizatori>();
            this.CatreMagazin_ComenziAprovizionari = new HashSet<ComenziAprovizionari>();
            this.DeLaDepozit_ComenziAprovizionari1 = new HashSet<ComenziAprovizionari>();
            this.CatreDepozit_ComenziAprovizionari2 = new HashSet<ComenziAprovizionari>();
        }
    
        public int Id { get; set; }
        public string Denumire { get; set; }
        public string Oras { get; set; }
        public string Adresa { get; set; }
        public string Email { get; set; }
        public bool EsteDepozitCentral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventar> Inventar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilizatori> Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComenziAprovizionari> CatreMagazin_ComenziAprovizionari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComenziAprovizionari> DeLaDepozit_ComenziAprovizionari1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComenziAprovizionari> CatreDepozit_ComenziAprovizionari2 { get; set; }
    }
}
