//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OchelariDeSoareView
    {
        public int Id { get; set; }
        public string Cod { get; set; }
        public string Denumire { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string EstePolarizat { get; set; }
        public decimal Pret { get; set; }
    }
}
