//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preturi
    {
        public int Id { get; set; }
        public decimal Valoare { get; set; }
        public System.DateTime DataActualizare { get; set; }
        public bool EsteUtilizatAcum { get; set; }
        public int IdProdus { get; set; }
    
        public virtual Produse Produse { get; set; }
    }
}
