//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produse()
        {
            this.DetaliiProdus = new HashSet<DetaliiProdus>();
            this.Inventar = new HashSet<Inventar>();
            this.Preturi = new HashSet<Preturi>();
            this.RandComenziProduse = new HashSet<RandComenziProduse>();
        }
    
        public int Id { get; set; }
        public string Cod { get; set; }
        public string Denumire { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public LicentaApp.Domain.ValueObjects.TipProdus TipProdus { get; set; }
        public int IdFurnizor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiProdus> DetaliiProdus { get; set; }
        public virtual Furnizori Furnizori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventar> Inventar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preturi> Preturi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandComenziProduse> RandComenziProduse { get; set; }
    }
}
