//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandComenziProduse
    {
        public int Id { get; set; }
        public int Cantitate { get; set; }
        public int IdComanda { get; set; }
        public int IdProdus { get; set; }
        public Nullable<LicentaApp.Domain.ValueObjects.TipTratament> TipTratement { get; set; }
        public Nullable<LicentaApp.Domain.ValueObjects.TipCuloare> TipCuloare { get; set; }
    
        public virtual Comenzi Comenzi { get; set; }
        public virtual Produse Produse { get; set; }
    }
}
