//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandComenziAprovizionareProduse
    {
        public int Id { get; set; }
        public int IdProdus { get; set; }
        public int IdComanda { get; set; }
        public int CantitateCeruta { get; set; }
        public Nullable<int> CantitatePrimita { get; set; }
    
        public virtual ComenziAprovizionari ComenziAprovizionari { get; set; }
        public virtual Produse Produse { get; set; }
    }
}
