//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViziteMedicale
    {
        public int IdComandaVizitaMedicala { get; set; }
        public int DistantaPupilara { get; set; }
        public Nullable<int> SferaDistantaStang { get; set; }
        public Nullable<int> SferaAproapeStang { get; set; }
        public Nullable<int> CilindruStang { get; set; }
        public Nullable<int> AxStang { get; set; }
        public Nullable<int> PrismaStang { get; set; }
        public Nullable<int> SferaDistantaDrept { get; set; }
        public Nullable<int> SferaAproapeDrept { get; set; }
        public Nullable<int> CilindruDrept { get; set; }
        public Nullable<int> AxDrept { get; set; }
        public Nullable<int> PrismaDrept { get; set; }
    
        public virtual Comenzi Comenzi { get; set; }
    }
}
