//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViziteMedicale
    {
        public int IdComandaVizitaMedicala { get; set; }
        public decimal DistantaPupilara { get; set; }
        public Nullable<decimal> SferaDistantaStang { get; set; }
        public Nullable<decimal> SferaAproapeStang { get; set; }
        public Nullable<decimal> CilindruStang { get; set; }
        public Nullable<decimal> AxStang { get; set; }
        public Nullable<decimal> PrismaStang { get; set; }
        public Nullable<decimal> SferaDistantaDrept { get; set; }
        public Nullable<decimal> SferaAproapeDrept { get; set; }
        public Nullable<decimal> CilindruDrept { get; set; }
        public Nullable<decimal> AxDrept { get; set; }
        public Nullable<decimal> PrismaDrept { get; set; }
    
        public virtual Comenzi Comenzi { get; set; }
    }
}
